### ISSUE TITLE
Doesn't build on Node.js 12.x.x

### ISSUE THREAD

**Issue by Hri7566** [multiplayerpiano/mpp-frontend-ts#2]
This repository does not build using Node.js 12.

This is an unintended side effect of setting up the CI workflow, but nonetheless is still an issue.

We may **remove the Node.js 12 CI action**, as it is not needed (Node.js 14.17.3 is the current LTS release).

**Comment by Hri7566** [comment]
I forgot to add that this is causing the rest of the builds to continue in the CI flow.

**Comment by electrashave** [comment]
I used Node.js v12.22.3 to build it on my end with no problems, although I'm on Linux

**Comment by BopItFreak** [comment]
It works for me on node v12.18.3. 

Is node even involved in this project anyway? You're supposed to run npm run build to build the project.

**Comment by Hri7566** [comment]
This issue is for the CI build, not local.

**Comment by BopItFreak** [comment]
What's the Cl build?

**Comment by Hri7566** [comment]
Continuous integration tests the code so it can be used in production. I set up the repository so GitHub will do this for us, and we can use stuff like jest to make sure the code works the way we want it to. The only thing is that node 12 is not LTS anymore, so I was suggesting we remove it, but I was asking for approval first

**Comment by BopItFreak** [comment]
Yeah sure do whatever you want to make it give me a green check mark. It's
cool.
